name: fitnessapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  fl_chart: ^1.1.1
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.8.5
  flutter_native_splash: ^2.3.1
  readmore: ^3.0.0
  calendar_agenda: ^0.0.2+3
  hive_flutter: ^1.1.0
  
  flutter_local_notifications: ^17.1.2 


  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0

  google_sign_in: ^7.2.0

  http: ^1.5.0

  camera: ^0.11.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  intl: ^0.17.0

  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#010101"
  image: assets/images/app_logo.png
  android_12:
    color: "#ffffff"
    color_dark: "#010101"
    image: assets/images/app_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
