// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBztxm0edQ75ZouKsujCKzFwasV7hNbQYo',
    appId: '1:1011533277601:web:8395fd3e7cd1b0831c03e0',
    messagingSenderId: '1011533277601',
    projectId: 'egouser-d77d2',
    authDomain: 'egouser-d77d2.firebaseapp.com',
    storageBucket: 'egouser-d77d2.firebasestorage.app',
    measurementId: 'G-DGWK93GD4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqwJDi1z5sasLrhDKDwRxp4azh6jivik',
    appId: '1:1011533277601:android:2fb6da23fef429ff1c03e0',
    messagingSenderId: '1011533277601',
    projectId: 'egouser-d77d2',
    storageBucket: 'egouser-d77d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWeRRPwwDk_cRwc7g1OdWg8zpl_6MtvQ',
    appId: '1:1011533277601:ios:3e016412313f9c721c03e0',
    messagingSenderId: '1011533277601',
    projectId: 'egouser-d77d2',
    storageBucket: 'egouser-d77d2.firebasestorage.app',
    iosBundleId: 'com.example.ego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWeRRPwwDk_cRwc7g1OdWg8zpl_6MtvQ',
    appId: '1:1011533277601:ios:3e016412313f9c721c03e0',
    messagingSenderId: '1011533277601',
    projectId: 'egouser-d77d2',
    storageBucket: 'egouser-d77d2.firebasestorage.app',
    iosBundleId: 'com.example.ego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBztxm0edQ75ZouKsujCKzFwasV7hNbQYo',
    appId: '1:1011533277601:web:068686c4788835421c03e0',
    messagingSenderId: '1011533277601',
    projectId: 'egouser-d77d2',
    authDomain: 'egouser-d77d2.firebaseapp.com',
    storageBucket: 'egouser-d77d2.firebasestorage.app',
    measurementId: 'G-XFKEFNKTJN',
  );
}
