// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalXS4pQFbDU6kuxY8aNyDnK3XJNzWKLs',
    appId: '1:586180299581:web:924edcba6cb9b9693dd354',
    messagingSenderId: '586180299581',
    projectId: 'egogym-aad03',
    authDomain: 'egogym-aad03.firebaseapp.com',
    databaseURL: 'https://egogym-aad03-default-rtdb.firebaseio.com',
    storageBucket: 'egogym-aad03.firebasestorage.app',
    measurementId: 'G-NPR50CMPL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5t-LGjpPeCL-_LlO-1YUd9ce_faKXKk',
    appId: '1:586180299581:android:443ea65067c3b0563dd354',
    messagingSenderId: '586180299581',
    projectId: 'egogym-aad03',
    databaseURL: 'https://egogym-aad03-default-rtdb.firebaseio.com',
    storageBucket: 'egogym-aad03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKArF0mFiICXPHkgXEgrbmulSeS5og-ho',
    appId: '1:586180299581:ios:d1f730a2319ae62b3dd354',
    messagingSenderId: '586180299581',
    projectId: 'egogym-aad03',
    databaseURL: 'https://egogym-aad03-default-rtdb.firebaseio.com',
    storageBucket: 'egogym-aad03.firebasestorage.app',
    androidClientId: '586180299581-8626kb9a8hktaafqsj85k07nrjmegi0t.apps.googleusercontent.com',
    iosClientId: '586180299581-ne5slo2ta4jsc4htl5dk2d577316vs5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKArF0mFiICXPHkgXEgrbmulSeS5og-ho',
    appId: '1:586180299581:ios:d1f730a2319ae62b3dd354',
    messagingSenderId: '586180299581',
    projectId: 'egogym-aad03',
    databaseURL: 'https://egogym-aad03-default-rtdb.firebaseio.com',
    storageBucket: 'egogym-aad03.firebasestorage.app',
    androidClientId: '586180299581-8626kb9a8hktaafqsj85k07nrjmegi0t.apps.googleusercontent.com',
    iosClientId: '586180299581-ne5slo2ta4jsc4htl5dk2d577316vs5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCalXS4pQFbDU6kuxY8aNyDnK3XJNzWKLs',
    appId: '1:586180299581:web:a97ff888df76b1c13dd354',
    messagingSenderId: '586180299581',
    projectId: 'egogym-aad03',
    authDomain: 'egogym-aad03.firebaseapp.com',
    databaseURL: 'https://egogym-aad03-default-rtdb.firebaseio.com',
    storageBucket: 'egogym-aad03.firebasestorage.app',
    measurementId: 'G-4J991TH7CX',
  );

}